version: '3'

services:

  redis:
    image: redis:latest

  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: gunicorn -b 0.0.0.0:5000 run:flask
    restart: always
    ports:
      - "5000:80"
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - data-volume:/db
      - .:/app
    env_file:
      - cfg.env


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A WebDownloader.jobs.worker.celery worker --loglevel=INFO
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - data-volume:/db
    env_file:
      - docker.env


volumes:
  data-volume: