version: '3'

services:

  redis:
    image: redis:latest

  api:
    build:
      context: WebDownloader
      dockerfile: Dockerfile
    working_dir: /app
    command: gunicorn -b 0.0.0.0:5000 app:flaskInstance
    restart: always
    ports:
      - "5000:5000"
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - data-volume:/db
    env_file:
      - docker.env

  vue:
    build:
      context: Frontend
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - data-volume:/db

  worker:
    build:
      context: WebDownloader
      dockerfile: Dockerfile
    command: celery -A WebDownloader.jobs.worker.celery worker --loglevel=INFO

    depends_on:
      - redis
    links:
      - redis
    volumes:
      - data-volume:/db
    env_file:
      - docker.env


volumes:
  data-volume:
