apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates an NEG after an Ingress is created
spec:
  selector:
    io.kompose.service: api
  clusterIP: None
  ports:
    - name: api # Actually, no port is needed.
      port: 80
      targetPort: 80