apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: api
        app: webapp
    spec:
      containers:
      - args:
          - gunicorn
          - wsgi:app
          - --config=gunicorn_config.py
          - --bind
          - 0.0.0.0:80
          - --proxy-allow-from
          - "*"
          - --forwarded-allow-ips
          - "*"
          - --proxy-protocol
          - --log-level
          - debug
        env:
        - name: APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: APP_ENVIRONMENT
              name: prodconfig
        - name: DATA_LOCATION
          valueFrom:
            configMapKeyRef:
              key: DATA_LOCATION
              name: prodconfig
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              key: FLASK_APP
              name: prodconfig
        - name: FLASK_DEBUG
          valueFrom:
            configMapKeyRef:
              key: FLASK_DEBUG
              name: prodconfig
        image: gcr.io/jnp2-docker/api:latest
        imagePullPolicy: ""
        name: api
        ports:
        - containerPort: 80
        resources: {}
        workingDir: /app/
      restartPolicy: Always
status: {}
