apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -v
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: vue
  name: vue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vue
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -v
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: vue
    spec:
      containers:
      - image: vue
        imagePullPolicy: ""
        name: vue
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /db
          name: data-volume
        workingDir: /app
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-volume
status: {}
