apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -v
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -v
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      volumes:
        - name: temps
          emptyDir: {}
      containers:
      - args:
        - python
        - -m
        - celery
        - -A
        - WebDownloader.core.jobs.worker.celery
        - worker
        - --loglevel=INFO
        env:
        - name: APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: APP_ENVIRONMENT
              name: prodconfig
        - name: DATA_LOCATION
          valueFrom:
            configMapKeyRef:
              key: DATA_LOCATION
              name: prodconfig
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              key: FLASK_APP
              name: prodconfig
        - name: FLASK_DEBUG
          valueFrom:
            configMapKeyRef:
              key: FLASK_DEBUG
              name: prodconfig
        image: gcr.io/jnp2-docker/api:latest
        imagePullPolicy: ""
        name: worker
        resources: {}
        workingDir: /app
        volumeMounts:
          - name: temps
            mountPath: /db

      restartPolicy: Always
      serviceAccountName: ""
status: {}
